language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - find $GOPATH
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.5.1
    - source qt-5.5.1.env
    - cd tests/qimmutabletests
    - qpm install
    - qmake
    - make
    - ls
    - ./qimmutabletests
    - valgrind --leak-check=full --show-reachable=yes ./qimmutabletests
  
