language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - cat /etc/apt/sources.list
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551
    - sudo add-apt-repository --yes "deb http://download.opensuse.org/repositories/home:/benlau/xUbuntu_15.10 ./"
    - cat /etc/apt/sources.list
    - sudo apt-get update
    - apt-cache search qt5
    - sudo apt-get install --force-yes -qq qt55quickcontrols  qt55declarative qt55script qt55graphicaleffects qpm valgrind
    - sh -e /etc/init.d/xvfb start
script:
    - source /opt/qt55/bin/qt55-env.sh 
    - cd tests/immutablelistmodeltests
    - qpm install
    - qmake
    - make
    - ls
    - ./immutablelistmodel
    - valgrind --leak-check=full --show-reachable=yes ./immutablelistmodel QSyncableTests
  
